name: Uiua tests

on:
  push:
    paths:
      - uiua/**
      - .github/workflows/uiua-tests.yaml
  pull_request:
    paths:
      - uiua/**
      - .github/workflows/uiua-tests.yaml

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./uiua
    steps:
      - uses: actions/checkout@v5

      - name: Install Rust and Cargo
        uses: dtolnay/rust-toolchain@stable

      - name: Install Uiua
        run: cargo install uiua --version 0.18.0-dev.4

      - name: Run uiua tests
        run: uiua run tests/test_solutions.ua
        env:
          UIUA_RECURSION_LIMIT: 1000
